# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nmcfadde/Legend

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nmcfadde/Legend

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nmcfadde/Legend/CMakeFiles /home/nmcfadde/Legend/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nmcfadde/Legend/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Legend

# Build rule for target.
Legend: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Legend
.PHONY : Legend

# fast build rule for target.
Legend/fast:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/build
.PHONY : Legend/fast

Legend.o: Legend.cc.o

.PHONY : Legend.o

# target to build an object file
Legend.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/Legend.cc.o
.PHONY : Legend.cc.o

Legend.i: Legend.cc.i

.PHONY : Legend.i

# target to preprocess a source file
Legend.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/Legend.cc.i
.PHONY : Legend.cc.i

Legend.s: Legend.cc.s

.PHONY : Legend.s

# target to generate assembly for a file
Legend.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/Legend.cc.s
.PHONY : Legend.cc.s

src/LegendActionInitialization.o: src/LegendActionInitialization.cc.o

.PHONY : src/LegendActionInitialization.o

# target to build an object file
src/LegendActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendActionInitialization.cc.o
.PHONY : src/LegendActionInitialization.cc.o

src/LegendActionInitialization.i: src/LegendActionInitialization.cc.i

.PHONY : src/LegendActionInitialization.i

# target to preprocess a source file
src/LegendActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendActionInitialization.cc.i
.PHONY : src/LegendActionInitialization.cc.i

src/LegendActionInitialization.s: src/LegendActionInitialization.cc.s

.PHONY : src/LegendActionInitialization.s

# target to generate assembly for a file
src/LegendActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendActionInitialization.cc.s
.PHONY : src/LegendActionInitialization.cc.s

src/LegendAnalysis.o: src/LegendAnalysis.cc.o

.PHONY : src/LegendAnalysis.o

# target to build an object file
src/LegendAnalysis.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendAnalysis.cc.o
.PHONY : src/LegendAnalysis.cc.o

src/LegendAnalysis.i: src/LegendAnalysis.cc.i

.PHONY : src/LegendAnalysis.i

# target to preprocess a source file
src/LegendAnalysis.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendAnalysis.cc.i
.PHONY : src/LegendAnalysis.cc.i

src/LegendAnalysis.s: src/LegendAnalysis.cc.s

.PHONY : src/LegendAnalysis.s

# target to generate assembly for a file
src/LegendAnalysis.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendAnalysis.cc.s
.PHONY : src/LegendAnalysis.cc.s

src/LegendDetectorConstruction.o: src/LegendDetectorConstruction.cc.o

.PHONY : src/LegendDetectorConstruction.o

# target to build an object file
src/LegendDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendDetectorConstruction.cc.o
.PHONY : src/LegendDetectorConstruction.cc.o

src/LegendDetectorConstruction.i: src/LegendDetectorConstruction.cc.i

.PHONY : src/LegendDetectorConstruction.i

# target to preprocess a source file
src/LegendDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendDetectorConstruction.cc.i
.PHONY : src/LegendDetectorConstruction.cc.i

src/LegendDetectorConstruction.s: src/LegendDetectorConstruction.cc.s

.PHONY : src/LegendDetectorConstruction.s

# target to generate assembly for a file
src/LegendDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendDetectorConstruction.cc.s
.PHONY : src/LegendDetectorConstruction.cc.s

src/LegendDetectorMessenger.o: src/LegendDetectorMessenger.cc.o

.PHONY : src/LegendDetectorMessenger.o

# target to build an object file
src/LegendDetectorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendDetectorMessenger.cc.o
.PHONY : src/LegendDetectorMessenger.cc.o

src/LegendDetectorMessenger.i: src/LegendDetectorMessenger.cc.i

.PHONY : src/LegendDetectorMessenger.i

# target to preprocess a source file
src/LegendDetectorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendDetectorMessenger.cc.i
.PHONY : src/LegendDetectorMessenger.cc.i

src/LegendDetectorMessenger.s: src/LegendDetectorMessenger.cc.s

.PHONY : src/LegendDetectorMessenger.s

# target to generate assembly for a file
src/LegendDetectorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendDetectorMessenger.cc.s
.PHONY : src/LegendDetectorMessenger.cc.s

src/LegendEMPhysics.o: src/LegendEMPhysics.cc.o

.PHONY : src/LegendEMPhysics.o

# target to build an object file
src/LegendEMPhysics.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendEMPhysics.cc.o
.PHONY : src/LegendEMPhysics.cc.o

src/LegendEMPhysics.i: src/LegendEMPhysics.cc.i

.PHONY : src/LegendEMPhysics.i

# target to preprocess a source file
src/LegendEMPhysics.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendEMPhysics.cc.i
.PHONY : src/LegendEMPhysics.cc.i

src/LegendEMPhysics.s: src/LegendEMPhysics.cc.s

.PHONY : src/LegendEMPhysics.s

# target to generate assembly for a file
src/LegendEMPhysics.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendEMPhysics.cc.s
.PHONY : src/LegendEMPhysics.cc.s

src/LegendEventAction.o: src/LegendEventAction.cc.o

.PHONY : src/LegendEventAction.o

# target to build an object file
src/LegendEventAction.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendEventAction.cc.o
.PHONY : src/LegendEventAction.cc.o

src/LegendEventAction.i: src/LegendEventAction.cc.i

.PHONY : src/LegendEventAction.i

# target to preprocess a source file
src/LegendEventAction.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendEventAction.cc.i
.PHONY : src/LegendEventAction.cc.i

src/LegendEventAction.s: src/LegendEventAction.cc.s

.PHONY : src/LegendEventAction.s

# target to generate assembly for a file
src/LegendEventAction.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendEventAction.cc.s
.PHONY : src/LegendEventAction.cc.s

src/LegendEventMessenger.o: src/LegendEventMessenger.cc.o

.PHONY : src/LegendEventMessenger.o

# target to build an object file
src/LegendEventMessenger.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendEventMessenger.cc.o
.PHONY : src/LegendEventMessenger.cc.o

src/LegendEventMessenger.i: src/LegendEventMessenger.cc.i

.PHONY : src/LegendEventMessenger.i

# target to preprocess a source file
src/LegendEventMessenger.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendEventMessenger.cc.i
.PHONY : src/LegendEventMessenger.cc.i

src/LegendEventMessenger.s: src/LegendEventMessenger.cc.s

.PHONY : src/LegendEventMessenger.s

# target to generate assembly for a file
src/LegendEventMessenger.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendEventMessenger.cc.s
.PHONY : src/LegendEventMessenger.cc.s

src/LegendGeneralPhysics.o: src/LegendGeneralPhysics.cc.o

.PHONY : src/LegendGeneralPhysics.o

# target to build an object file
src/LegendGeneralPhysics.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendGeneralPhysics.cc.o
.PHONY : src/LegendGeneralPhysics.cc.o

src/LegendGeneralPhysics.i: src/LegendGeneralPhysics.cc.i

.PHONY : src/LegendGeneralPhysics.i

# target to preprocess a source file
src/LegendGeneralPhysics.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendGeneralPhysics.cc.i
.PHONY : src/LegendGeneralPhysics.cc.i

src/LegendGeneralPhysics.s: src/LegendGeneralPhysics.cc.s

.PHONY : src/LegendGeneralPhysics.s

# target to generate assembly for a file
src/LegendGeneralPhysics.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendGeneralPhysics.cc.s
.PHONY : src/LegendGeneralPhysics.cc.s

src/LegendMaxTimeCuts.o: src/LegendMaxTimeCuts.cc.o

.PHONY : src/LegendMaxTimeCuts.o

# target to build an object file
src/LegendMaxTimeCuts.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendMaxTimeCuts.cc.o
.PHONY : src/LegendMaxTimeCuts.cc.o

src/LegendMaxTimeCuts.i: src/LegendMaxTimeCuts.cc.i

.PHONY : src/LegendMaxTimeCuts.i

# target to preprocess a source file
src/LegendMaxTimeCuts.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendMaxTimeCuts.cc.i
.PHONY : src/LegendMaxTimeCuts.cc.i

src/LegendMaxTimeCuts.s: src/LegendMaxTimeCuts.cc.s

.PHONY : src/LegendMaxTimeCuts.s

# target to generate assembly for a file
src/LegendMaxTimeCuts.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendMaxTimeCuts.cc.s
.PHONY : src/LegendMaxTimeCuts.cc.s

src/LegendMinEkineCuts.o: src/LegendMinEkineCuts.cc.o

.PHONY : src/LegendMinEkineCuts.o

# target to build an object file
src/LegendMinEkineCuts.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendMinEkineCuts.cc.o
.PHONY : src/LegendMinEkineCuts.cc.o

src/LegendMinEkineCuts.i: src/LegendMinEkineCuts.cc.i

.PHONY : src/LegendMinEkineCuts.i

# target to preprocess a source file
src/LegendMinEkineCuts.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendMinEkineCuts.cc.i
.PHONY : src/LegendMinEkineCuts.cc.i

src/LegendMinEkineCuts.s: src/LegendMinEkineCuts.cc.s

.PHONY : src/LegendMinEkineCuts.s

# target to generate assembly for a file
src/LegendMinEkineCuts.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendMinEkineCuts.cc.s
.PHONY : src/LegendMinEkineCuts.cc.s

src/LegendMuonPhysics.o: src/LegendMuonPhysics.cc.o

.PHONY : src/LegendMuonPhysics.o

# target to build an object file
src/LegendMuonPhysics.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendMuonPhysics.cc.o
.PHONY : src/LegendMuonPhysics.cc.o

src/LegendMuonPhysics.i: src/LegendMuonPhysics.cc.i

.PHONY : src/LegendMuonPhysics.i

# target to preprocess a source file
src/LegendMuonPhysics.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendMuonPhysics.cc.i
.PHONY : src/LegendMuonPhysics.cc.i

src/LegendMuonPhysics.s: src/LegendMuonPhysics.cc.s

.PHONY : src/LegendMuonPhysics.s

# target to generate assembly for a file
src/LegendMuonPhysics.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendMuonPhysics.cc.s
.PHONY : src/LegendMuonPhysics.cc.s

src/LegendPMTSD.o: src/LegendPMTSD.cc.o

.PHONY : src/LegendPMTSD.o

# target to build an object file
src/LegendPMTSD.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPMTSD.cc.o
.PHONY : src/LegendPMTSD.cc.o

src/LegendPMTSD.i: src/LegendPMTSD.cc.i

.PHONY : src/LegendPMTSD.i

# target to preprocess a source file
src/LegendPMTSD.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPMTSD.cc.i
.PHONY : src/LegendPMTSD.cc.i

src/LegendPMTSD.s: src/LegendPMTSD.cc.s

.PHONY : src/LegendPMTSD.s

# target to generate assembly for a file
src/LegendPMTSD.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPMTSD.cc.s
.PHONY : src/LegendPMTSD.cc.s

src/LegendPMTSDHit.o: src/LegendPMTSDHit.cc.o

.PHONY : src/LegendPMTSDHit.o

# target to build an object file
src/LegendPMTSDHit.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPMTSDHit.cc.o
.PHONY : src/LegendPMTSDHit.cc.o

src/LegendPMTSDHit.i: src/LegendPMTSDHit.cc.i

.PHONY : src/LegendPMTSDHit.i

# target to preprocess a source file
src/LegendPMTSDHit.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPMTSDHit.cc.i
.PHONY : src/LegendPMTSDHit.cc.i

src/LegendPMTSDHit.s: src/LegendPMTSDHit.cc.s

.PHONY : src/LegendPMTSDHit.s

# target to generate assembly for a file
src/LegendPMTSDHit.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPMTSDHit.cc.s
.PHONY : src/LegendPMTSDHit.cc.s

src/LegendPhysicsList.o: src/LegendPhysicsList.cc.o

.PHONY : src/LegendPhysicsList.o

# target to build an object file
src/LegendPhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPhysicsList.cc.o
.PHONY : src/LegendPhysicsList.cc.o

src/LegendPhysicsList.i: src/LegendPhysicsList.cc.i

.PHONY : src/LegendPhysicsList.i

# target to preprocess a source file
src/LegendPhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPhysicsList.cc.i
.PHONY : src/LegendPhysicsList.cc.i

src/LegendPhysicsList.s: src/LegendPhysicsList.cc.s

.PHONY : src/LegendPhysicsList.s

# target to generate assembly for a file
src/LegendPhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPhysicsList.cc.s
.PHONY : src/LegendPhysicsList.cc.s

src/LegendPrimaryGeneratorAction.o: src/LegendPrimaryGeneratorAction.cc.o

.PHONY : src/LegendPrimaryGeneratorAction.o

# target to build an object file
src/LegendPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPrimaryGeneratorAction.cc.o
.PHONY : src/LegendPrimaryGeneratorAction.cc.o

src/LegendPrimaryGeneratorAction.i: src/LegendPrimaryGeneratorAction.cc.i

.PHONY : src/LegendPrimaryGeneratorAction.i

# target to preprocess a source file
src/LegendPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPrimaryGeneratorAction.cc.i
.PHONY : src/LegendPrimaryGeneratorAction.cc.i

src/LegendPrimaryGeneratorAction.s: src/LegendPrimaryGeneratorAction.cc.s

.PHONY : src/LegendPrimaryGeneratorAction.s

# target to generate assembly for a file
src/LegendPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendPrimaryGeneratorAction.cc.s
.PHONY : src/LegendPrimaryGeneratorAction.cc.s

src/LegendRunAction.o: src/LegendRunAction.cc.o

.PHONY : src/LegendRunAction.o

# target to build an object file
src/LegendRunAction.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendRunAction.cc.o
.PHONY : src/LegendRunAction.cc.o

src/LegendRunAction.i: src/LegendRunAction.cc.i

.PHONY : src/LegendRunAction.i

# target to preprocess a source file
src/LegendRunAction.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendRunAction.cc.i
.PHONY : src/LegendRunAction.cc.i

src/LegendRunAction.s: src/LegendRunAction.cc.s

.PHONY : src/LegendRunAction.s

# target to generate assembly for a file
src/LegendRunAction.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendRunAction.cc.s
.PHONY : src/LegendRunAction.cc.s

src/LegendScintSD.o: src/LegendScintSD.cc.o

.PHONY : src/LegendScintSD.o

# target to build an object file
src/LegendScintSD.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendScintSD.cc.o
.PHONY : src/LegendScintSD.cc.o

src/LegendScintSD.i: src/LegendScintSD.cc.i

.PHONY : src/LegendScintSD.i

# target to preprocess a source file
src/LegendScintSD.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendScintSD.cc.i
.PHONY : src/LegendScintSD.cc.i

src/LegendScintSD.s: src/LegendScintSD.cc.s

.PHONY : src/LegendScintSD.s

# target to generate assembly for a file
src/LegendScintSD.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendScintSD.cc.s
.PHONY : src/LegendScintSD.cc.s

src/LegendScintSDHit.o: src/LegendScintSDHit.cc.o

.PHONY : src/LegendScintSDHit.o

# target to build an object file
src/LegendScintSDHit.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendScintSDHit.cc.o
.PHONY : src/LegendScintSDHit.cc.o

src/LegendScintSDHit.i: src/LegendScintSDHit.cc.i

.PHONY : src/LegendScintSDHit.i

# target to preprocess a source file
src/LegendScintSDHit.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendScintSDHit.cc.i
.PHONY : src/LegendScintSDHit.cc.i

src/LegendScintSDHit.s: src/LegendScintSDHit.cc.s

.PHONY : src/LegendScintSDHit.s

# target to generate assembly for a file
src/LegendScintSDHit.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendScintSDHit.cc.s
.PHONY : src/LegendScintSDHit.cc.s

src/LegendSpecialCuts.o: src/LegendSpecialCuts.cc.o

.PHONY : src/LegendSpecialCuts.o

# target to build an object file
src/LegendSpecialCuts.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSpecialCuts.cc.o
.PHONY : src/LegendSpecialCuts.cc.o

src/LegendSpecialCuts.i: src/LegendSpecialCuts.cc.i

.PHONY : src/LegendSpecialCuts.i

# target to preprocess a source file
src/LegendSpecialCuts.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSpecialCuts.cc.i
.PHONY : src/LegendSpecialCuts.cc.i

src/LegendSpecialCuts.s: src/LegendSpecialCuts.cc.s

.PHONY : src/LegendSpecialCuts.s

# target to generate assembly for a file
src/LegendSpecialCuts.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSpecialCuts.cc.s
.PHONY : src/LegendSpecialCuts.cc.s

src/LegendStackingAction.o: src/LegendStackingAction.cc.o

.PHONY : src/LegendStackingAction.o

# target to build an object file
src/LegendStackingAction.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendStackingAction.cc.o
.PHONY : src/LegendStackingAction.cc.o

src/LegendStackingAction.i: src/LegendStackingAction.cc.i

.PHONY : src/LegendStackingAction.i

# target to preprocess a source file
src/LegendStackingAction.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendStackingAction.cc.i
.PHONY : src/LegendStackingAction.cc.i

src/LegendStackingAction.s: src/LegendStackingAction.cc.s

.PHONY : src/LegendStackingAction.s

# target to generate assembly for a file
src/LegendStackingAction.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendStackingAction.cc.s
.PHONY : src/LegendStackingAction.cc.s

src/LegendSteppingAction.o: src/LegendSteppingAction.cc.o

.PHONY : src/LegendSteppingAction.o

# target to build an object file
src/LegendSteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSteppingAction.cc.o
.PHONY : src/LegendSteppingAction.cc.o

src/LegendSteppingAction.i: src/LegendSteppingAction.cc.i

.PHONY : src/LegendSteppingAction.i

# target to preprocess a source file
src/LegendSteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSteppingAction.cc.i
.PHONY : src/LegendSteppingAction.cc.i

src/LegendSteppingAction.s: src/LegendSteppingAction.cc.s

.PHONY : src/LegendSteppingAction.s

# target to generate assembly for a file
src/LegendSteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSteppingAction.cc.s
.PHONY : src/LegendSteppingAction.cc.s

src/LegendSteppingMessenger.o: src/LegendSteppingMessenger.cc.o

.PHONY : src/LegendSteppingMessenger.o

# target to build an object file
src/LegendSteppingMessenger.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSteppingMessenger.cc.o
.PHONY : src/LegendSteppingMessenger.cc.o

src/LegendSteppingMessenger.i: src/LegendSteppingMessenger.cc.i

.PHONY : src/LegendSteppingMessenger.i

# target to preprocess a source file
src/LegendSteppingMessenger.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSteppingMessenger.cc.i
.PHONY : src/LegendSteppingMessenger.cc.i

src/LegendSteppingMessenger.s: src/LegendSteppingMessenger.cc.s

.PHONY : src/LegendSteppingMessenger.s

# target to generate assembly for a file
src/LegendSteppingMessenger.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSteppingMessenger.cc.s
.PHONY : src/LegendSteppingMessenger.cc.s

src/LegendSteppingVerbose.o: src/LegendSteppingVerbose.cc.o

.PHONY : src/LegendSteppingVerbose.o

# target to build an object file
src/LegendSteppingVerbose.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSteppingVerbose.cc.o
.PHONY : src/LegendSteppingVerbose.cc.o

src/LegendSteppingVerbose.i: src/LegendSteppingVerbose.cc.i

.PHONY : src/LegendSteppingVerbose.i

# target to preprocess a source file
src/LegendSteppingVerbose.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSteppingVerbose.cc.i
.PHONY : src/LegendSteppingVerbose.cc.i

src/LegendSteppingVerbose.s: src/LegendSteppingVerbose.cc.s

.PHONY : src/LegendSteppingVerbose.s

# target to generate assembly for a file
src/LegendSteppingVerbose.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendSteppingVerbose.cc.s
.PHONY : src/LegendSteppingVerbose.cc.s

src/LegendTrackingAction.o: src/LegendTrackingAction.cc.o

.PHONY : src/LegendTrackingAction.o

# target to build an object file
src/LegendTrackingAction.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendTrackingAction.cc.o
.PHONY : src/LegendTrackingAction.cc.o

src/LegendTrackingAction.i: src/LegendTrackingAction.cc.i

.PHONY : src/LegendTrackingAction.i

# target to preprocess a source file
src/LegendTrackingAction.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendTrackingAction.cc.i
.PHONY : src/LegendTrackingAction.cc.i

src/LegendTrackingAction.s: src/LegendTrackingAction.cc.s

.PHONY : src/LegendTrackingAction.s

# target to generate assembly for a file
src/LegendTrackingAction.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendTrackingAction.cc.s
.PHONY : src/LegendTrackingAction.cc.s

src/LegendTrajectory.o: src/LegendTrajectory.cc.o

.PHONY : src/LegendTrajectory.o

# target to build an object file
src/LegendTrajectory.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendTrajectory.cc.o
.PHONY : src/LegendTrajectory.cc.o

src/LegendTrajectory.i: src/LegendTrajectory.cc.i

.PHONY : src/LegendTrajectory.i

# target to preprocess a source file
src/LegendTrajectory.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendTrajectory.cc.i
.PHONY : src/LegendTrajectory.cc.i

src/LegendTrajectory.s: src/LegendTrajectory.cc.s

.PHONY : src/LegendTrajectory.s

# target to generate assembly for a file
src/LegendTrajectory.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendTrajectory.cc.s
.PHONY : src/LegendTrajectory.cc.s

src/LegendUserEventInformation.o: src/LegendUserEventInformation.cc.o

.PHONY : src/LegendUserEventInformation.o

# target to build an object file
src/LegendUserEventInformation.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendUserEventInformation.cc.o
.PHONY : src/LegendUserEventInformation.cc.o

src/LegendUserEventInformation.i: src/LegendUserEventInformation.cc.i

.PHONY : src/LegendUserEventInformation.i

# target to preprocess a source file
src/LegendUserEventInformation.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendUserEventInformation.cc.i
.PHONY : src/LegendUserEventInformation.cc.i

src/LegendUserEventInformation.s: src/LegendUserEventInformation.cc.s

.PHONY : src/LegendUserEventInformation.s

# target to generate assembly for a file
src/LegendUserEventInformation.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendUserEventInformation.cc.s
.PHONY : src/LegendUserEventInformation.cc.s

src/LegendUserTrackInformation.o: src/LegendUserTrackInformation.cc.o

.PHONY : src/LegendUserTrackInformation.o

# target to build an object file
src/LegendUserTrackInformation.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendUserTrackInformation.cc.o
.PHONY : src/LegendUserTrackInformation.cc.o

src/LegendUserTrackInformation.i: src/LegendUserTrackInformation.cc.i

.PHONY : src/LegendUserTrackInformation.i

# target to preprocess a source file
src/LegendUserTrackInformation.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendUserTrackInformation.cc.i
.PHONY : src/LegendUserTrackInformation.cc.i

src/LegendUserTrackInformation.s: src/LegendUserTrackInformation.cc.s

.PHONY : src/LegendUserTrackInformation.s

# target to generate assembly for a file
src/LegendUserTrackInformation.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/LegendUserTrackInformation.cc.s
.PHONY : src/LegendUserTrackInformation.cc.s

src/OpWLS.o: src/OpWLS.cc.o

.PHONY : src/OpWLS.o

# target to build an object file
src/OpWLS.cc.o:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/OpWLS.cc.o
.PHONY : src/OpWLS.cc.o

src/OpWLS.i: src/OpWLS.cc.i

.PHONY : src/OpWLS.i

# target to preprocess a source file
src/OpWLS.cc.i:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/OpWLS.cc.i
.PHONY : src/OpWLS.cc.i

src/OpWLS.s: src/OpWLS.cc.s

.PHONY : src/OpWLS.s

# target to generate assembly for a file
src/OpWLS.cc.s:
	$(MAKE) -f CMakeFiles/Legend.dir/build.make CMakeFiles/Legend.dir/src/OpWLS.cc.s
.PHONY : src/OpWLS.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Legend"
	@echo "... Legend.o"
	@echo "... Legend.i"
	@echo "... Legend.s"
	@echo "... src/LegendActionInitialization.o"
	@echo "... src/LegendActionInitialization.i"
	@echo "... src/LegendActionInitialization.s"
	@echo "... src/LegendAnalysis.o"
	@echo "... src/LegendAnalysis.i"
	@echo "... src/LegendAnalysis.s"
	@echo "... src/LegendDetectorConstruction.o"
	@echo "... src/LegendDetectorConstruction.i"
	@echo "... src/LegendDetectorConstruction.s"
	@echo "... src/LegendDetectorMessenger.o"
	@echo "... src/LegendDetectorMessenger.i"
	@echo "... src/LegendDetectorMessenger.s"
	@echo "... src/LegendEMPhysics.o"
	@echo "... src/LegendEMPhysics.i"
	@echo "... src/LegendEMPhysics.s"
	@echo "... src/LegendEventAction.o"
	@echo "... src/LegendEventAction.i"
	@echo "... src/LegendEventAction.s"
	@echo "... src/LegendEventMessenger.o"
	@echo "... src/LegendEventMessenger.i"
	@echo "... src/LegendEventMessenger.s"
	@echo "... src/LegendGeneralPhysics.o"
	@echo "... src/LegendGeneralPhysics.i"
	@echo "... src/LegendGeneralPhysics.s"
	@echo "... src/LegendMaxTimeCuts.o"
	@echo "... src/LegendMaxTimeCuts.i"
	@echo "... src/LegendMaxTimeCuts.s"
	@echo "... src/LegendMinEkineCuts.o"
	@echo "... src/LegendMinEkineCuts.i"
	@echo "... src/LegendMinEkineCuts.s"
	@echo "... src/LegendMuonPhysics.o"
	@echo "... src/LegendMuonPhysics.i"
	@echo "... src/LegendMuonPhysics.s"
	@echo "... src/LegendPMTSD.o"
	@echo "... src/LegendPMTSD.i"
	@echo "... src/LegendPMTSD.s"
	@echo "... src/LegendPMTSDHit.o"
	@echo "... src/LegendPMTSDHit.i"
	@echo "... src/LegendPMTSDHit.s"
	@echo "... src/LegendPhysicsList.o"
	@echo "... src/LegendPhysicsList.i"
	@echo "... src/LegendPhysicsList.s"
	@echo "... src/LegendPrimaryGeneratorAction.o"
	@echo "... src/LegendPrimaryGeneratorAction.i"
	@echo "... src/LegendPrimaryGeneratorAction.s"
	@echo "... src/LegendRunAction.o"
	@echo "... src/LegendRunAction.i"
	@echo "... src/LegendRunAction.s"
	@echo "... src/LegendScintSD.o"
	@echo "... src/LegendScintSD.i"
	@echo "... src/LegendScintSD.s"
	@echo "... src/LegendScintSDHit.o"
	@echo "... src/LegendScintSDHit.i"
	@echo "... src/LegendScintSDHit.s"
	@echo "... src/LegendSpecialCuts.o"
	@echo "... src/LegendSpecialCuts.i"
	@echo "... src/LegendSpecialCuts.s"
	@echo "... src/LegendStackingAction.o"
	@echo "... src/LegendStackingAction.i"
	@echo "... src/LegendStackingAction.s"
	@echo "... src/LegendSteppingAction.o"
	@echo "... src/LegendSteppingAction.i"
	@echo "... src/LegendSteppingAction.s"
	@echo "... src/LegendSteppingMessenger.o"
	@echo "... src/LegendSteppingMessenger.i"
	@echo "... src/LegendSteppingMessenger.s"
	@echo "... src/LegendSteppingVerbose.o"
	@echo "... src/LegendSteppingVerbose.i"
	@echo "... src/LegendSteppingVerbose.s"
	@echo "... src/LegendTrackingAction.o"
	@echo "... src/LegendTrackingAction.i"
	@echo "... src/LegendTrackingAction.s"
	@echo "... src/LegendTrajectory.o"
	@echo "... src/LegendTrajectory.i"
	@echo "... src/LegendTrajectory.s"
	@echo "... src/LegendUserEventInformation.o"
	@echo "... src/LegendUserEventInformation.i"
	@echo "... src/LegendUserEventInformation.s"
	@echo "... src/LegendUserTrackInformation.o"
	@echo "... src/LegendUserTrackInformation.i"
	@echo "... src/LegendUserTrackInformation.s"
	@echo "... src/OpWLS.o"
	@echo "... src/OpWLS.i"
	@echo "... src/OpWLS.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

